import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  globalIgnores(['dist']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs['recommended-latest'],
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
  },
  {
    // shadcn/ui primitives are generated by `npx shadcn@latest add` and
    // deliberately export their cva variants (buttonVariants,
    // badgeVariants) alongside the component — that's the upstream API,
    // and these files are not hand-edited (see CLAUDE.md). The rule only
    // affects how surgically react-refresh can hot-swap a file in dev;
    // it has no effect on the production bundle. Scoped to this
    // directory so the rule keeps applying to our own components.
    files: ['src/components/ui/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
])
